name = "todo"
compatibility_date = "2025-10-16"
main = ".svelte-kit/cloudflare/_worker.js"

[build]
command = "pnpm run build"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
# Base URL for the Cloudflare KV REST endpoints (include account + namespace path)
CF_KV_API_BASE = "https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/storage/kv/namespaces/<NAMESPACE_ID>"

# Secrets such as CF_KV_API_TOKEN must be configured via `wrangler secret put` and are not checked into source.
